<?php
defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . '/libraries/REST_Controller.php';

class Autenticador extends REST_Controller {

  public function index_post()
  {
    $email = $this->post('email');
    $senha = $this->post('senha');

    $this->db->where('email', $email);
    $this->db->where('senha', $senha);
    $usuario = $this->db->get('admin')->first_row();

    if($usuario) {
      $dados = array(
        'id'=> $usuario->id,
        'nome'=> $usuario->nome,
        'email'=> $usuario->email,
        'logado'=> TRUE
      );//array com os dados do cookie
      $this->session->set_userdata($dados);
    }

    $message = [
      'id' => $usuario->id, // Automatically generated by the model
      'nome' => $usuario->nome,
      'email' => $usuario->email,
      'senha' => $usuario->senha,
      'message' => 'logado com sucesso'
    ];

    if ($usuario) {
      $this->set_response($message, REST_Controller::HTTP_OK);
    }
    else
    {
      // Set the response and exit
      $this->response([
          'status' => FALSE,
          'message' => 'usuario não encontrado'
      ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
    }
  }

  public function sair_get()
  {
    $this->session->sess_destroy();
    $this->set_response('saida com sucesso', REST_Controller::HTTP_OK);
  }
}

/* End of file Autenticador.php */
/* Location: ./application/controllers/Autenticador.php */